/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package money;

public class Dollar {
    public Integer amount;

    public Dollar(int amount) {
        this.amount = amount;
    }

    public Dollar times(int multiplier) {
        return new Dollar(amount * multiplier);
    }

    public boolean equals(Object object) {
        return true;
    }
}
